-- Users Table
create table public.users (
  id uuid default gen_random_uuid() primary key,
  username text unique not null,
  password text not null, -- In a real app, hash this!
  name text not null,
  title text,
  phone text,
  image text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Lands Table
create table public.lands (
  id bigint generated by default as identity primary key,
  title text not null,
  location text not null,
  size text not null,
  price numeric not null,
  image_url text,
  description text,
  features text[],
  ada text,
  parsel text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Proposals Table
create table public.proposals (
  id text primary key, -- Custom short ID
  customer_name text not null,
  sender_name text,
  sender_title text,
  sender_phone text,
  sender_image text,
  valid_until timestamp with time zone,
  created_by text not null, -- references users(username)
  items jsonb not null, -- Stores the array of proposal items
  global_notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Optional but recommended for security later)
alter table public.users enable row level security;
alter table public.lands enable row level security;
alter table public.proposals enable row level security;

-- Policies (For development, allow all access. Tweak for prod)
create policy "Public users can read everything" on public.users for select using (true);
create policy "Public users can read everything" on public.lands for select using (true);
create policy "Public users can read everything" on public.proposals for select using (true);

create policy "Anon can insert/update/delete" on public.users for all using (true);
create policy "Anon can insert/update/delete" on public.lands for all using (true);
create policy "Anon can insert/update/delete" on public.proposals for all using (true);
